name: Eleutheromania
favicon: null
layout_spectrum: 0.36621
typography_spectrum: 0
title: Eleutheromania
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74849d'
    - '#fafafa'
    - '#b3c5d3'
    - '#0f0e09'
    - '#584d2f'
  brandStrength: 0
  lightness: 0.6422966858372092
  saturation: 0.720970154274255
  rhythmicContrast: 0.13102633086964488
purpose: []
