typography_spectrum: 0
content_rating:
  adult: false
color:
  brandColors:
    - '#1c3089'
    - '#ffeefe'
    - '#5dabdc'
    - '#91def2'
    - '#f067e9'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.720970154274255
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39007
analytics:
  google: UA-77378645-1
  facebook: null
  twitter: null
author:
  name: Anand Arun
  email: anandarun99@gmail.com
  url: www.anandtravels.net
name: Eleutheromania
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Eleutheromania
purpose: []
