name: Eleutheromania
favicon: null
layout_spectrum: 0.36845
typography_spectrum: 0
title: Eleutheromania
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77378645-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0625
  lightness: 0.6422966858372092
  saturation: 0.720970154274255
  rhythmicContrast: 0.13102633086964488
purpose: []
