layout_spectrum: 0.7670139349065721
typography_spectrum: 0.4030622048303485
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.39928669878281653
  lightness: 0.07039161445572972
  saturation: 0.2198166218586266
  rhythmicContrast: 0.06487965281121433
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-77378645-1
  facebook: null
  twitter: null
author:
  url: www.anandtravels.net
  name: Anand Arun
  email: anandarun99@gmail.com
name: Eleutheromania
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The urge to travel indefinietly
purpose: []
