name: Eleutheromania
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Eleutheromania
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77378645-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c3089'
    - '#ffeefe'
    - '#5dabdc'
    - '#91def2'
    - '#f067e9'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.720970154274255
  rhythmicContrast: 0.13102633086964488
purpose: []
